name: yanalytics_firebase
description: Y—Analytics implementation for Firebase SDK
version: 1.0.0
publish_to: none
repository: https://github.com/yml-org/yanalytics-firebase-flutter

environment:
  sdk: '>=2.19.6 <3.0.0'

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  mocktail: ^0.3.0
  flutter_test:
    sdk: flutter
  lints: ^2.0.0
  test: ^1.21.0

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.10.0
  firebase_analytics: ^10.2.0
  yanalytics:
    git:
      url: https://github.com/yml-org/yanalytics-flutter.git
      ref: main